In [71]:
# ライブラリのインポート
import pandas as pd
from datetime import datetime as dt

# CSVファイル読込、日付型項目を索引、時系列データ集計(parse_dates)
frame1 = pd.read_csv('C:\\Users\\Owner\\Pandas-Exercises7\FILE.csv', index_col=['取引日'], parse_dates=True)

In [72]:
# 時系列データの最初を表示
frame1.head()

            取引量
取引日
2020-01-01  100
2020-01-02  100
2020-01-03  100
2020-01-04  100
2020-01-05  100

In [73]:
# 時系列データの最後を表示
frame1.tail()

            取引量
取引日
2020-05-27  500
2020-05-28  500
2020-05-29  500
2020-05-30  500
2020-05-31  500

In [74]:
# 時系列データの特定期間を表示
frame1.loc['2020-01-08':'2020-01-12']

            取引量
取引日
2020-01-08  100
2020-01-09  100
2020-01-10  100
2020-01-11  100
2020-01-12  100

In [75]:
# 時系列データの週単位集計(平均値)の最初を表示
frame1.resample(rule='W').mean().head()

                   取引量
取引日
2020-01-05  100.000000
2020-01-12  100.000000
2020-01-19  100.000000
2020-01-26  100.000000
2020-02-02  128.571429

In [76]:
# 時系列データの週単位集計(合計値)の最初を表示
frame1.resample(rule='W').sum().head()

            取引量
取引日
2020-01-05  500
2020-01-12  700
2020-01-19  700
2020-01-26  700
2020-02-02  900

In [77]:
# 時系列データの月単位集計(平均値)の最初を表示
frame1.resample(rule='M').mean().head()

            取引量
取引日
2020-01-31  100
2020-02-29  200
2020-03-31  300
2020-04-30  400
2020-05-31  500

In [78]:
# 時系列データの月単位集計(合計値)の最初を表示
frame1.resample(rule='M').sum().head()

              取引量
取引日
2020-01-31   3100
2020-02-29   5800
2020-03-31   9300
2020-04-30  12000
2020-05-31  15500